export const PERMISSIONS = {
	APPOINTMENT: {
		VIEW: 'APPOINTMENT.VIEW',
		CREATE: 'APPOINTMENT.CREATE',
		UPDATE: 'APPOINTMENT.UPDATE',
		DELETE: 'APPOINTMENT.DELETE',
		CONFIRM: 'APPOINTMENT.CONFIRM',
		WORK_APPROVAL_UPDATE: 'APPOINTMENT.WORK_APPROVAL.UPDATE',
		VIEW_ALL: 'APPOINTMENT.VIEW_ALL'
	},
	APPOINTMENT_CARD: {
		VIEW: 'APPOINTMENT_CARD.VIEW',
		CREATE: 'APPOINTMENT_CARD.CREATE',
		UPDATE: 'APPOINTMENT_CARD.UPDATE',
		DELETE: 'APPOINTMENT_CARD.DELETE',
		GENERATE_DOCUMENT: 'APPOINTMENT_CARD.GENERATE_DOCUMENT'
	},
	CLIENT: {
		VIEW: 'CLIENT.VIEW',
		CREATE: 'CLIENT.CREATE',
		UPDATE: 'CLIENT.UPDATE',
		DELETE: 'CLIENT.DELETE',
		STATUS_UPDATE: 'CLIENT.STATUS.UPDATE',
		DOCUMENTS_VIEW: 'CLIENT.DOCUMENTS.VIEW',
		DOCUMENTS_UPLOAD: 'CLIENT.DOCUMENTS.UPLOAD',
		DOCUMENTS_DELETE: 'CLIENT.DOCUMENTS.DELETE',
		INCIDENT_VIEW: 'CLIENT.INCIDENT.VIEW',
		INCIDENT_CREATE: 'CLIENT.INCIDENT.CREATE',
		INCIDENT_UPDATE: 'CLIENT.INCIDENT.UPDATE',
		INCIDENT_DELETE: 'CLIENT.INCIDENT.DELETE',
		INCIDENT_CONFIRM: 'CLIENT.INCIDENT.CONFIRM',
		DIAGNOSIS_VIEW: 'CLIENT.DIAGNOSIS.VIEW',
		DIAGNOSIS_CREATE: 'CLIENT.DIAGNOSIS.CREATE',
		DIAGNOSIS_UPDATE: 'CLIENT.DIAGNOSIS.UPDATE',
		DIAGNOSIS_DELETE: 'CLIENT.DIAGNOSIS.DELETE',
		MEDICATION_VIEW: 'CLIENT.MEDICATION.VIEW',
		MEDICATION_CREATE: 'CLIENT.MEDICATION.CREATE',
		MEDICATION_UPDATE: 'CLIENT.MEDICATION.UPDATE',
		MEDICATION_DELETE: 'CLIENT.MEDICATION.DELETE',
		EMERGENCY_CONTACT_VIEW: 'CLIENT.EMERGENCY_CONTACT.VIEW',
		EMERGENCY_CONTACT_CREATE: 'CLIENT.EMERGENCY_CONTACT.CREATE',
		EMERGENCY_CONTACT_UPDATE: 'CLIENT.EMERGENCY_CONTACT.UPDATE',
		EMERGENCY_CONTACT_DELETE: 'CLIENT.EMERGENCY_CONTACT.DELETE',
		INVOLVED_EMPLOYEE_VIEW: 'CLIENT.INVOLVED_EMPLOYEE.VIEW',
		INVOLVED_EMPLOYEE_CREATE: 'CLIENT.INVOLVED_EMPLOYEE.CREATE',
		INVOLVED_EMPLOYEE_UPDATE: 'CLIENT.INVOLVED_EMPLOYEE.UPDATE',
		INVOLVED_EMPLOYEE_DELETE: 'CLIENT.INVOLVED_EMPLOYEE.DELETE',
		PROGRESS_REPORT_VIEW: 'CLIENT.PROGRESS_REPORT.VIEW',
		PROGRESS_REPORT_CREATE: 'CLIENT.PROGRESS_REPORT.CREATE',
		PROGRESS_REPORT_UPDATE: 'CLIENT.PROGRESS_REPORT.UPDATE',
		PROGRESS_REPORT_DELETE: 'CLIENT.PROGRESS_REPORT.DELETE',
		AI_PROGRESS_REPORT_VIEW: 'CLIENT.AI_PROGRESS_REPORT.VIEW',
		AI_PROGRESS_REPORT_GENERATE: 'CLIENT.AI_PROGRESS_REPORT.GENERATE',
		AI_PROGRESS_REPORT_CONFIRM: 'CLIENT.AI_PROGRESS_REPORT.CONFIRM',
		CARE_PLAN_VIEW: 'CLIENT.CARE_PLAN.VIEW',
		CARE_PLAN_CREATE: 'CLIENT.CARE_PLAN.CREATE',
		CARE_PLAN_UPDATE: 'CLIENT.CARE_PLAN.UPDATE',
		CARE_PLAN_DELETE: 'CLIENT.CARE_PLAN.DELETE'
	},
	CONTRACT: {
		VIEW: 'CONTRACT.VIEW',
		CREATE: 'CONTRACT.CREATE',
		UPDATE: 'CONTRACT.UPDATE',
		DELETE: 'CONTRACT.DELETE'
	},
	CONTRACT_TYPE: {
		VIEW: 'CONTRACT_TYPE.VIEW',
		CREATE: 'CONTRACT_TYPE.CREATE',
		DELETE: 'CONTRACT_TYPE.DELETE'
	},
	DASHBOARD: {
		VIEW: 'DASHBOARD.VIEW'
	},
	SETTINGS: {
		VIEW: 'SETTINGS.VIEW'
	},
	EMPLOYEE: {
		VIEW: 'EMPLOYEE.VIEW',
		CREATE: 'EMPLOYEE.CREATE',
		UPDATE: 'EMPLOYEE.UPDATE',
		DELETE: 'EMPLOYEE.DELETE',
		WORKING_HOURS_VIEW: 'EMPLOYEE.WORKING_HOURS.VIEW',
		CONTRACT_VIEW: 'EMPLOYEE.CONTRACT.VIEW',
		CONTRACT_UPDATE: 'EMPLOYEE.CONTRACT.UPDATE'
	},
	INCIDENT: {
		VIEW: 'INCIDENT.VIEW'
	},
	FINANCE: {
		VIEW: 'FINANCE.VIEW'
	},
	INVOICE: {
		VIEW: 'INVOICE.VIEW',
		CREATE: 'INVOICE.CREATE',
		UPDATE: 'INVOICE.UPDATE',
		DELETE: 'INVOICE.DELETE',
		PAYMENT_VIEW: 'INVOICE.PAYMENT.VIEW',
		PAYMENT_CREATE: 'INVOICE.PAYMENT.CREATE',
		PAYMENT_UPDATE: 'INVOICE.PAYMENT.UPDATE',
		PAYMENT_DELETE: 'INVOICE.PAYMENT.DELETE'
	},
	ORGANISATION: {
		VIEW: 'ORGANISATION.VIEW',
		CREATE: 'ORGANISATION.CREATE',
		UPDATE: 'ORGANISATION.UPDATE'
	},
	LOCATION: {
		VIEW: 'LOCATION.VIEW',
		CREATE: 'LOCATION.CREATE',
		UPDATE: 'LOCATION.UPDATE',
		DELETE: 'LOCATION.DELETE'
	},
	PROFILE: {
		VIEW: 'PROFILE.VIEW'
	},
	REGISTRATION_FORM: {
		VIEW: 'REGISTRATION_FORM.VIEW',
		UPDATE: 'REGISTRATION_FORM.UPDATE',
		DELETE: 'REGISTRATION_FORM.DELETE'
	},
	ROLES: {
		VIEW: 'ROLES.VIEW',
		CREATE: 'ROLES.CREATE',
		UPDATE: 'ROLES.UPDATE',
		DELETE: 'ROLES.DELETE',
		ASSIGN: 'ROLES.ASSIGN'
	},
	PERMISSION: {
		VIEW: 'PERMISSIONS.VIEW',
		CREATE: 'PERMISSIONS.CREATE',
		UPDATE: 'PERMISSIONS.UPDATE',
		DELETE: 'PERMISSIONS.DELETE',
		GRANT: 'PERMISSIONS.GRANT'
	},
	SCHEDULE: {
		VIEW: 'SCHEDULE.VIEW',
		CREATE: 'SCHEDULE.CREATE',
		UPDATE: 'SCHEDULE.UPDATE',
		DELETE: 'SCHEDULE.DELETE'
	},
	SHIFT: {
		VIEW: 'SHIFT.VIEW',
		CREATE: 'SHIFT.CREATE',
		UPDATE: 'SHIFT.UPDATE',
		DELETE: 'SHIFT.DELETE'
	},
	SENDER: {
		VIEW: 'SENDER.VIEW',
		CREATE: 'SENDER.CREATE',
		UPDATE: 'SENDER.UPDATE'
	},
	TEST: {
		VIEW: 'TEST.VIEW'
	},
	CARE_COORDINATION: {
		VIEW: 'CARE_COORDINATION.VIEW'
	},
	REPORTS: {
		VIEW: 'REPORTS.VIEW'
	},
	AUDIT: {
		LOG_VIEW: 'AUDIT.LOG.VIEW'
	}
} as const;

type ValueOf<T> = T[keyof T];
export type PermissionCategory = keyof typeof PERMISSIONS;
export type PermissionValue = ValueOf<{
	[K in keyof typeof PERMISSIONS]: ValueOf<(typeof PERMISSIONS)[K]>;
}>;
